language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"

# command to install dependencies
install:
   - pip --quiet install py

# command to run tests
script:
  - make test

notifications:
  email: false
